package com.natife.streaming


const val MAIN_API_QUALIFIER = "MAIN_API"
const val MAIN_API_CLIENT_QUALIFIER = "MAIN_API_CLIENT"
const val PREFS_AUTH_QUALIFIER = "PREFS_AUTH_QUALIFIER"
const val PREFS_SETTINGS_QUALIFIER = "PREFS_SETTINGS_QUALIFIER"
const val PREFS_MATCH_SETTINGS_QUALIFIER = "PREFS_MATCH_SETTINGS_QUALIFIER"
const val PREFS_SEARCH_QUALIFIER = "PREFS_SEARCH_QUALIFIER"
const val CLIENT_ID = "ott-android"
const val GRAND_TYPE = "password"

const val DATABASE_NAME = "APP_DATABASE"

const val PREFS_AUTH_NAME = "auth.prefs"
const val PREFS_SETTINGS_NAME = "settings.prefs"
const val PREFS_MATCH_SETTINGS_NAME = "settings.match_prefs"
const val PREFS_SEARCH_NAME = "settings.search_prefs"

const val AUTH_API_URL = "https://auth.instat.tv/token"
const val AUTHORIZATION = "Authorization"
const val BEARER = "Bearer"
const val TOKEN_FIELD_NAME = "x-auth-token"

const val API_LOGIN = "auth_user"
const val API_REGISTER = "create_user"
const val API_ACCOUNT = "get_user_info"
const val API_MATCHES = "get_matches"
const val API_SPORTS = "get_sport_list"
const val API_MATCH_PROFILE = "get_tournament_info"
const val API_TOURNAMENT_LIST = "get_tournament_list"
const val API_TRANSLATE = "param_lexical"
const val API_MATCH_INFO = "get_match_info"
const val API_MATCH_POPUP = "ott_match_popup"
const val API_ACTIONS = "ott_match_popup_actions"
const val API_TOURNAMENT = "get_tournament_info"
const val API_SEARCH = "get_objects"
const val API_SECOND = "get_user_match_second"
const val API_PLAYERS_ACTIONS = "ott_match_popup_player_playlist"
const val API_PLAYER_INFO = "get_player_info"
const val API_SAVE_DELETE_FAVORITE = "save_user_favorite"
const val API_GET_FAVORITES = "get_user_favorites"
const val API_TOURNAMENT_MATCHES = "get_tournament_matches"
const val API_PLAYER_MATCHES = "get_player_matches"
const val API_TEAM_MATCHES = "get_team_matches"
const val API_TEAM_INFO = "get_team_info"
const val API_SAVE_USER_MATCH_SECOND = "save_user_match_second"
const val API_GET_USER_MATCH_SECOND = "get_user_match_second"
const val API_GET_USER_PREFERENCES = "get_user_preferences"
const val API_SAVE_USER_PREFERENCES = "save_user_preferences"
const val API_MATCH_SUBSCRIPTION = "get_match_subscriptions"
const val API_REFRESH_TOKEN = "refresh_token"

const val VIDEO_AUTO = "Auto"
const val VIDEO_1080 = "1080"
const val VIDEO_720 = "720"
const val VIDEO_480 = "480"
const val VIDEO_400 = "400"
const val VIDEO_240 = "240"
